In [1]:
import numpy as np
import pandas as pd

In [2]:
ga_full_applicants = pd.read_csv('/Users/javanreuto/Desktop/PPP Info Challenge/ppp_applicants_ga_full.csv')
ga_full_applicants

,name,amount,state,address,city,zip,naics_code,business_type,jobs_retained,date_approved,...,project_county_name,project_state,project_zip,originating_lender_city,originating_lender_state,loan_status_date,originating_lender_location_id,lmi_indicator,forgiveness_amount,forgiveness_date
0,LUMMUS CORPORATION,2000000.00,GA,225 Bourne Blvd,Savannah,31408-9586,333249.0,Corporation,294,2021-02-20,...,CHATHAM,GA,31408-9586,CHICAGO,IL,NaN,116998,N,NaN,NaN
1,COLIANT SOLUTIONS INC.,1294555.00,GA,2703 Brickton North Dr,Buford,30518-9101,541519.0,Corporation,63,2021-01-31,...,GWINNETT,GA,30518-9101,COLUMBUS,GA,NaN,19248,Y,NaN,NaN
2,YOHE PLUMBING INC,729509.00,GA,1120 Franke Court N/A,Augusta,30909,238220.0,Corporation,105,2021-03-12,...,RICHMOND,GA,30909,PHOENIXVILLE,PA,NaN,121536,N,NaN,NaN
3,LEWIS COLOR LITHOGRAPHERS INC,571193.40,GA,30 Joe Kennedy Blvd,Statesboro,30458-3417,323111.0,Corporation,49,2021-02-02,...,BULLOCH,GA,30458-3417,COLUMBUS,GA,NaN,19248,N,NaN,NaN
4,"ALMA PAK INTERNATIONAL, LLC",472700.00,GA,230 PINEVIEW RD,ALMA,31510-4326,445230.0,Partnership,37,2020-04-10,...,BACON,GA,31510-4326,ALMA,GA,2021-01-08,17811,N,475877.59,2020-12-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
553823,PAUL CLARK,757.00,GA,609 Fern St,Waycross,31501-3210,561492.0,Independent Contractors,1,2021-04-30,...,WARE,GA,31501-3210,Miami,FL,NaN,529192,N,NaN,NaN
553824,DEWEY GRIFFIN,700.00,GA,245 Moray Rd,Alma,31510-4371,111940.0,Sole Proprietorship,1,2021-04-02,...,BACON,GA,31510-4371,ALMA,GA,2021-09-24,17808,N,702.61,2021-08-23
553825,HAYDEN WHITLOW,582.71,GA,2696 Douglas Ct NW,Acworth,30101-3677,561730.0,Independent Contractors,1,2021-02-19,...,COBB,GA,30101-3677,HINTON,OK,NaN,58771,N,NaN,NaN
553826,KEVIN LEWIS,270.00,GA,4830 Northway Drive Northeast,Sandy Springs,30342-2424,541990.0,Sole Proprietorship,1,2020-08-03,...,FULTON,GA,30342-2424,TEANECK,NJ,NaN,456756,N,NaN,NaN
553827,ARTEAYA TAYLOR,12052.00,GA,Sedona Loop,Hampton,30253,531210.0,Sole Proprietorship,1,2021-02-04,...,HENRY,GA,30253,TEANECK,NJ,NaN,456756,Y,NaN,NaN

In [4]:
ga_full_applicants.isna().sum()

name                                   1
amount                                 0
state                                  0
address                                1
city                                   0
zip                                    0
naics_code                          2340
business_type                         41
jobs_retained                          0
date_approved                          0
lender                                 0
congressional_district                 5
loan_number                            0
sba_office_code                        0
processing_method                      0
loan_status                            0
term                                   0
sba_guaranty_percentage                0
initial_approval_amount                0
current_approval_amount                0
undisbursed_amount                   115
servicing_lender_location_id           0
servicing_lender_name                  0
servicing_lender_address               0
servicing_lender_city                  0
servicing_lender_state                 0
servicing_lender_zip                   0
rural_urban_indicator                  0
hubzone_indicator                      0
business_age_description               0
project_city                           0
project_county_name                    6
project_state                          0
project_zip                            0
originating_lender_city                0
originating_lender_state               0
loan_status_date                  273239
originating_lender_location_id         0
lmi_indicator                          0
forgiveness_amount                182631
forgiveness_date                  182631
dtype: int64

In [3]:
ga_full_date = pd.Series(ga_full_applicants['date_approved'].unique()).sort_values(ascending=True)
ga_full_date

224    2020-04-03
158    2020-04-04
58     2020-04-05
148    2020-04-06
31     2020-04-07
          ...
175    2021-05-29
234    2021-06-15
220    2021-06-22
221    2021-06-29
235    2021-06-30
Length: 237, dtype: object

In [8]:
ga_full_applicants['city'] = ga_full_applicants['city'].apply(lambda x: x.upper())

name, address, city, business type, loan status, lender, servicing_lender_name, servicing_lender_city, business age description, project_city, project_county_name, originating lender city

In [19]:
def uppercase_columns(df, column):
    df[column] = df[column].str.upper()

uppercase_columns(ga_full_applicants, 'name')
uppercase_columns(ga_full_applicants, 'address')
uppercase_columns(ga_full_applicants, 'city')
uppercase_columns(ga_full_applicants, 'business_type')
uppercase_columns(ga_full_applicants, 'loan_status')
uppercase_columns(ga_full_applicants, 'lender')
uppercase_columns(ga_full_applicants, 'servicing_lender_name')
uppercase_columns(ga_full_applicants, 'servicing_lender_address')
uppercase_columns(ga_full_applicants, 'servicing_lender_city')
uppercase_columns(ga_full_applicants, 'business_age_description')
uppercase_columns(ga_full_applicants, 'project_city')
uppercase_columns(ga_full_applicants, 'project_county_name')
uppercase_columns(ga_full_applicants, 'originating_lender_city')

In [25]:
ga_removed_applicants = pd.read_excel('/Users/javanreuto/Desktop/PPP Info Challenge/ppp-removed-ga.xlsx')
ga_removed_applicants

,name,amount,state,address,city,zip,naics_code,business_type,jobs_retained,date_approved,...,project_county_name,project_state,project_zip,originating_lender_city,originating_lender_state,loan_status_date,originating_lender_location_id,lmi_indicator,forgiveness_amount,forgiveness_date
0,TRIPLE C CUSTOM CONCRETE LLC,43655.0,GA,106 Lisa Street East Dublin GA,East Dublin,31027,238990,Limited Liability Company(LLC),7,2021-05-11,...,LAURENS,GA,31027,Saint Petersburg,FL,2021-05-11,123499,Y,NaN,NaN
1,DAVIS LAWN CARE SERVICES,35000.0,GA,752 Savannah Ave N/A,Waynesboro,30830-1156,112910,Partnership,2,2021-05-12,...,BURKE,GA,30830-1156,ARLINGTON,MA,2021-05-12,262380,N,NaN,NaN
2,LONNIE RATLIFF,28949.0,GA,55 Maple St NW Apt 802,Atlanta,30314-4760,531390,Single Member LLC,5,2021-04-16,...,FULTON,GA,30314-4760,PHOENIXVILLE,PA,2021-04-16,121536,Y,NaN,NaN
3,DENARD TRIMBLE,20833.0,GA,727 Chapman St,Jonesboro,30238-5681,812111,Sole Proprietorship,1,2021-05-22,...,FAYETTE,GA,30238-5681,Brea,CA,2021-05-22,514546,Y,NaN,NaN
4,DANA VINES,20833.0,GA,3548 Tracey Dr,Duluth,30096-3861,311999,Sole Proprietorship,1,2021-03-20,...,GWINNETT,GA,30096-3861,Miami,FL,2021-03-20,529192,N,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25831,DONNELL WILSON,1950.0,GA,1000 Paces Ln,Woodstock,30189-4829,621511,Sole Proprietorship,1,2021-04-01,...,CHEROKEE,GA,30189-4829,Laguna Hills,CA,2021-04-01,509316,N,NaN,NaN
25832,MAMADOU DIOULDE DIALLO,1849.0,GA,7000 Roswell Rd Apt 252,Atlanta,30328-2389,485310,Independent Contractors,1,2021-05-21,...,FULTON,GA,30328-2389,Bedford,TX,2021-05-21,529472,N,NaN,NaN
25833,ANTHONY HARRIS,1245.0,GA,2849 Blount St,Atlanta,30344-3732,485310,Independent Contractors,1,2021-04-08,...,FULTON,GA,30344-3732,Bedford,TX,2021-04-08,529472,Y,NaN,NaN
25834,TAAHIRA ROBINSON,1075.0,GA,8541 Glendevon Ct,Riverdale,30274-4573,561110,Limited Liability Company(LLC),1,2021-05-11,...,CLAYTON,GA,30274-4573,Miami,FL,2021-05-11,529192,Y,NaN,NaN
25835,ERICA FERNANDEZ,787.0,GA,406 Nova Cir,Stockbridge,30281-3750,561720,Independent Contractors,1,2021-05-23,...,HENRY,GA,30281-3750,Bedford,TX,2021-05-23,529472,Y,NaN,NaN